# This is a basic workflow to help you get started with Actions

name: Upload to server.

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH Key
      run: |
         mkdir -p ~/.ssh/
         echo "$SSH_KEY" > ~/.ssh/prod.key
         chmod 600 ~/.ssh/prod.key
         cat >>~/.ssh/config <<END
         Host prod
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/prod.key
          StrictHostKeyChecking no
         END
      env:
       SSH_USER: ${{ secrets.SSH_USER }}
       SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       SSH_HOST: ${{ secrets.SSH_HOST }}
    
    - name: Git pull
      run: ssh prod 'cd ${{ secrets.HOME_DIR }} && git pull'
    
    - name: Install npm modules
      run: ssh prod 'cd ${{ secrets.HOME_DIR }} && npm install'

    - name: PM2 Stop
      run: ssh prod 'pm2 stop Bot'
      
    - name: PM2 Start
      run: ssh prod 'pm2 start Bot'
    
