# This is a basic workflow to help you get started with Actions

name: Build React Website and upload to to server

on: [push]

env:
  IMAGE_NAME: Melonbot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH Key
      run: |
         mkdir -p ~/.ssh/
         echo "$SSH_KEY" > ~/.ssh/prod.key
         chmod 600 ~/.ssh/prod.key
         cat >>~/.ssh/config <<END
         Host prod
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/prod.key
          StrictHostKeyChecking no
         END
      env:
       SSH_USER: ${{ secrets.SSH_USER }}
       SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       SSH_HOST: ${{ secrets.SSH_HOST }}
       
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
          node-version: '14'
    - run: npm run build      
    
    - name: Stop previous Docker configuration off server.
      run: ssh prod 'docker stop Melonbot'
      continue-on-error: true
    
    - name: Uninstall Docker configuration
      run: ssh prod 'docker rm Melonbot'
      continue-on-error: true
    
    - name: Git pull
      run: ssh prod 'cd ${{ secrets.HOME_DIR }} && git pull'
        
    - name: Build Docker Image
      run: ssh prod 'cd ${{ secrets.HOME_DIR }} && docker prune Melonbot && docker build --tag Melonbot
    
    - name: Run newly built docker image
      run: ssh prod 'docker run -d --name Melonbot \ 
          -v ${{ secrets.DOCKER_LOCATION }}/logs:/logs \
          -v ${{ secrets.DOCKER_LOCATION }}/error_logs:/error_logs \
          Melonbot'
      
    
